### ISSUE TITLE
[feat] 유저, 예매, 공연, 회차 엔티티 생성

### ISSUE THREAD

**Issue by move-hoon** [TEAM-BEAT/BEAT-Server#13]
## Feature Issue 📌

- 유저, 예매, 공연, 회차 엔티티를 생성합니다.

<br>

## Todo ✔️
- [x] 유저 엔티티 생성
- [x] 예매 엔티티 생성
- [x] 공연 엔티티 생성
- [x] 회차 엔티티 생성
