### ISSUE TITLE
[feat] 회원, 홍보, 등장인물, 스태프 엔티티 생성

### ISSUE THREAD

**Issue by hyerinhwang-sailin** [TEAM-BEAT/BEAT-Server#14]
## Feature Issue 📌
- 회원, 홍보, 등장인물, 스태프 엔티티를 생성합니다

<br>

## Todo ✔️

- [x]  회원 엔티티 생성
- [x]  홍보 엔티티 생성
- [x]  등장인물 엔티티 생성
- [x]  스태프 엔티티 생성
