### ISSUE TITLE
[feat] promotion 필드 추가 및 지난 공연 캐러샐 자동 삭제 구현

### ISSUE THREAD

**Issue by hyerinhwang-sailin** [TEAM-BEAT/BEAT-Server#172]
## Feature Issue 📌

promotion 필드 추가 및 지난 공연 캐러샐 자동 삭제 구현, 일부 api의 response 수정
<br>

## Todo ✔️

- [x]  promotion에 필요 필드 추가
- [x] 지난 공연 캐러샐 자동 삭제 구현
- [x] 공연 관리페이지 조회 시 공연 리스트에 duedate 같이 반환 및 duedate 기준 정렬
- [x] 공연상세페이지 조회 시 duedate 같이 반환
- [x] 공연 예매하기 시 필요한 상세정보 조회에서 스케쥴 별 duedate 반환
