### ISSUE TITLE
[refactor] schedule, staff, cast 수정 DTO 각각을 add, delete,update DTO로 세분화

### ISSUE THREAD

**Issue by move-hoon** [TEAM-BEAT/BEAT-Server#177]
### ID 생성의 책임이 클라이언트에 있음
- 공연 1에 회차를 1개 더 추가하려고 가정할 때, requestBody로 scheduleId를 줘야하는데, 마지막 회차아이디 + 1을 해서 줘야하는데 그걸 클라이언트에서는 알 수 없습니다.
- 또한, 여러 클라이언트가 동시에 새로운 회차를 추가하려고 할 때, 클라이언트들이 서버의 최신 상태를 알 수 없으므로 중복된 ID를 생성하거나, 올바르지 않은 ID를 생성할 가능성이 있습니다.
- schedule뿐만이 아닌, cast, staff에서도 동일한 문제가 발생합니다.

### ID 생성의 책임을 서버로 이전한다면?
- requestBody에 회차 아이디를 주지 않고, 서버가 자동으로 autoIncrement로 회차 ID를 생성하는 방법을 도입할 수 있는데, 이러면 회차를 삭제하려고 할 때 회차 ID를 requestBody 지정해주지 못하는 문제가 발생합니다.

### 회차 추가, 회차 삭제 API를 분리하면 되지 않나요?
- 현재 프로젝트의 공연 수정 로직 기획은 회차 추가 및 삭제를 버튼 1개로 동시에 수정할 수 있는 방법입니다. 따라서 추가와 삭제를 분리할 수 없습니다.

### 고안한 방법
1. UUID 도입
2. DTO 분리

### 최종 선택
- 2번 DTO 분리를 채택하게 되었습니다. 
- 이유는 UUID의 경우 ID 생성의 책임이 클라이언트에 있을 때, 마지막 회차아이디 + 1을 할 필요 없이 UUID를 생성해서 주면 되며 ID 중복문제도 해결이 됩니다.
- 하지만 schedule, cast, staff의 id를 모두 UUID로 바꿔야 하며, 시간 리소스가 너무 많이 소모가 됩니다.
- 따라서 기존 PerformanceUpdateRequest와  PerformanceUpdateResponse DTO 내부에 ScheduleUpdateRequest, CastUpdateRequest, StaffUpdateRequest, ScheduleUpdateResponse, CastUpdateResponse, StaffUpdateRespone를 각각 ADD, DELETE, UPDATE 요청 및 응답으로 세분화 하는 방법을 채택하게 되었습니다.
- 해당 방법을 사용한다면, 시간 리소스도 적으며 ID 생성의 책임을 서버로 이전했을 때, 삭제시에는 DeleteRequests에 id를 넣고, 업데이트시에는 UpdateRequests에 업데이트 하고자 하는 id와 정보들을 넣고, 추가시에는 AddRequests에 추가 정보를 넣고 id를 autoIncrement 하는 방식으로 한다면 문제는 해결됩니다.

<br>

## Todo ✔️

- [x]  기존 PerformanceUpdateRequest DTO 내부 ScheduleUpdateRequest, CastUpdateRequest, StaffUpdateRequest DTO 각각을 ADD. DELETE, UPDATE DTO로 세분화
- [x] 기존 PerformanceUpdateResponse DTO 내부 ScheduleUpdateResponse, CastUpdateResponse, StaffUpdateRespone DTO 각각을 ADD. DELETE, UPDATE DTO로 세분화
- [x] PerformanceUpdateService에서 추가, 삭제, 업데이트 작업을 각각의 리스트를 통해 처리하도록 수정
- [x] 예매자가 존재할 시 가격 정보를 수정하지 못하도록 하는 로직 추가
- [x] 예매자가 존재하지 않을 시 가격 정보를 수정할 수 있도록 하는 로직 추가
