### ISSUE TITLE
[refactor] schedule, staff, cast의 add, delete,update DTO를 하나의 DTO로 합치고 서비스 로직에서 add, delete, update를 판단하여 처리하도록 변경

### ISSUE THREAD

**Issue by move-hoon** [TEAM-BEAT/BEAT-Server#185]
### Why?
- 기존에 변경한 schedule, staff, cast의 add, delete, update DTO 세분화는 클라이언트에서 판단을 해서 보내줘야 해서, 책임이 클라이언트에 치중되어 있었습니다.
- 따라서 schedule, staff, cast의 add, delete, update DTO를 하나의 DTO로 합치고 서비스 레이어에서 add, delete, update를 판단하여 처리하도록 변경하고자 합니다.

### HOW?
- add, delete, update Request DTO를 하나의 Request DTO로 합치고 서비스 레이어에서 add, delete, update를 판단하여 주어진 로직을 수행합니다.
- for문을 돌려서 각 서비스 로직에 맞게끔 회차를 추가,삭제,변경합니다.
    - add시에는 scheduleId를 제외한  performanceDate, totalTicketCount, scheduleNumber를 보내줍니다.
    - delete시에는 아무것도 보내주지 않으며, 정보가 없기에 해당 회차는 삭제가 되게됩니다.
    - update시에는 scheduleId를 포함해서, performanceDate, totalTicketCount, scheduleNumber를 보내줍니다.

- add, delete, update Response DTO를 하나의 Response DTO로 합치고 id를 포함해서 현재 수정된 결과를 보내줍니다.
- scheduleNumber를 클라이언트 측에서 보내주는게 아닌 서버측에서 회차별 날짜로 재정렬하여 회차번호를 부여하는 작업을 추가합니다.

<br>

## Todo ✔️

- [x]  add, delete, update Request DTO를 하나의 Request DTO로 합치고 서비스 레이어에서 add, delete, update를 판단하여 주어진 로직을 수행하도록 변경
- [x] add, delete, update Response DTO를 하나의 Response DTO로 합치고 id를 포함해서 현재 수정된 결과를 보내주도록 변경
- [x] scheduleNumber를 클라이언트 측에서 보내주는게 아닌 서버측에서 회차별 날짜로 재정렬하여 회차번호를 부여하도록 변경
