### ISSUE TITLE
[feat] 어드민 기능 생성

### ISSUE THREAD

**Issue by move-hoon** [TEAM-BEAT/BEAT-Server#190]
### Why
- 기존에 타 파트의 부탁을 받아 처리해야 하는 작업(캐러셀 이미지 업로드, 각 공연 별 티켓 예매 수 조회 등)이 관리자 페이지가 존재하지 않아 직접 DB에서 확인을 한 후 타 파트에게 알려줘야만 했고, 이에 리소스가 많이 소요된다고 판단되어 어드민 기능을 도입하고자 합니다.
- 따라서 전반적인 유저 관리 및 데이터 처리 작업을 간편화하기 위해 어드민 기능을 만듭니다!

#### 해야할 일
1. 캐러셀 이미지 업로드 자동화(presigned-url)
2. 관리자 권한 부여(강제 탈퇴 가능)
3. 가입된 유저 정보 조회
4. 공연 별, 회차 별 예매한 티켓 상태(입금확인중/예매확정/예매취소) 조회
5. 각 공연 별, 회차 별 티켓 예매 수 조회
6. 악성 유저 강제 탈퇴 기능

#### 1안
- 타임리프를 사용해서 관리자 페이지를 작업합니다.

#### 2안
- 디자이너와 프론트와 협업해 관리자 페이지를 작업합니다.

<br>

## Todo ✔️

- [x] 캐러셀 이미지 업로드 자동화
- [x] 토큰 authorities에 관리자 권한 부여
- [x] 가입된 유저 정보 조회

## 2차 스프린트 Todo
- 공연 별, 회차 별 예매한 티켓 상태(입금확인중/예매확정/예매취소) 조회
- 각 공연 별, 회차 별 티켓 예매 수 조회
- 악성 유저 강제 탈퇴 기능
