### ISSUE TITLE
[feat] 예매 취소 soft delete 구현 및 입금 완료된 예매자 미입금으로 바꾸지 못하도록 변경

### ISSUE THREAD

**Issue by hyerinhwang-sailin** [TEAM-BEAT/BEAT-Server#191]
## Feature Issue 📌

예매 취소 soft delete 구현 및 입금 완료된 예매자 미입금으로 바꾸지 못하도록 변경

<br>

## Todo ✔️

- [x] 입금 완료된 예매자 미입금으로 바꾸지 못하도록 변경
- [x] 예매 상태 관련 enum 추가(입금확인중/예매확정/예매취소)
- [x] 예매 취소 soft delete 구현(1년 뒤 hard delete)
- [x] 예매 확인 페이지, 공연 관리 페이지에서 예매 취소 상태 확인 가능하도록 구현
