### ISSUE TITLE
[bug] 과거 스케쥴 등록 에러 처리

### ISSUE THREAD

**Issue by hyerinhwang-sailin** [TEAM-BEAT/BEAT-Server#211]
## Bug/Fix Issue 📌

과거 스케쥴을 포함한 공연을 등록하거나 공연 수정 시 과거 날짜로 수정하는 것, 과거 날짜의 스케쥴을 추가하는 것을 막는 에러 처리가 필요합니다.

<br>

## Todo ✔️

- [x]  공연 등록 관련 에러처리
- [x] 공연 수정 관련 - 회차 추가 시 에러처리
- [x] 공연 수정 관련 - 회차 수정 시 에러처리
