### ISSUE TITLE
[feat] Booking 엔티티 수정 및 환불/취소 요청 API 구현

### ISSUE THREAD

**Issue by hyerinhwang-sailin** [TEAM-BEAT/BEAT-Server#259]
## Feature Issue 📌

Booking 엔티티 수정 및 환불/취소 요청 API 구현
<br>

## Todo ✔️

- [x]  Booking 엔티티 수정
- [x] 입금완료 예매자 환불 요청 API 구현
- [x] 미입금/무료공연 예매자 취소 요청 API 구현
