### ISSUE TITLE
[feat] Ticket 관련 API 구현

### ISSUE THREAD

**Issue by hyerinhwang-sailin** [TEAM-BEAT/BEAT-Server#261]
## Feature Issue 📌

Ticket 관련 API 구현

<br>

## Todo ✔️

- [x] 입금여부 정보 수정 API : url 수정
- [x] 예매자 환불 처리 API : 기존 메이커의 예매취소처리 API를 수정
- [x] 예매자 삭제 API 추가
- [x] 예매자 목록 조회 API : dto 수정 및 정렬, 필터링 추가
- [x] 예매자 목록 검색 API
