### ISSUE TITLE
[refactor] 도메인형 디렉터리 구조 변경 및 운영 환경 분리

### ISSUE THREAD

**Issue by move-hoon** [TEAM-BEAT/BEAT-Server#4]
## Feature Issue 📌

- 도메인형 디렉터리 구조로 디렉터리 구성을 변경합니다
- 개발 서버와 운영 서버를 나눠서 운영 환경을 분리합니다.
<br>

## Todo ✔️

- [x] 최상위 레벨에서는 domain과 global로 패키징
- [x] domain 패키지에서는 도메인을 기준으로 하위 패키지를 구성
- [x] global 패키지에서는 프로젝트 전방위적으로 사용할 수 있는 클래스들로 구성
- [x] application.yml을 local, dev, prod로 분리
