### ISSUE TITLE
[feat] 전체 공연 목록 및 홍보 목록 조회 GET API 구현

### ISSUE THREAD

**Issue by hyerinhwang-sailin** [TEAM-BEAT/BEAT-Server#44]
## Feature Issue 📌
홈페이지에서 전체 공연 목록 및 홍보 목록 조회 GET API 구현

<br>

## Todo ✔️

- [x]  전체 공연 목록 및 홍보 목록 조회 GET API 구현
- [x] 공연 목록 due date가 적은 순으로 정렬
- [x] 회차별 due date 계산 로직 생성
- [x] 회차 중 due date가 가장 작은 due date을 홈화면에 노출 및 홈화면 정렬 기준으로 설정
