### ISSUE TITLE
[feat] 예매자 관리 API 구현

### ISSUE THREAD

**Issue by hyerinhwang-sailin** [TEAM-BEAT/BEAT-Server#49]
## Feature Issue 📌

- 메이커(회원)가 메이커의 공연을 예매한 예매자 목록을 조회하는 GET API
- 체크박스로 입금여부 정보 수정 후 “저장할게요” 버튼 눌러서 예매자 입금여부 정보를 수정하는 PUT API
- 예매자 중 일부를 선택해 “삭제할게요” 버튼을 눌러 삭제하는 DELETE API
<br>

## Todo ✔️

- [x]  메이커(회원)가 메이커의 공연을 예매한 예매자 목록을 조회하는 GET API 구현하기
- [x] 예매자 중 일부의 입금여부 정보를 수정하는 PUT API 구현
- [x] 예매자 중 일부를 삭제하는 DELETE API 구현
